package e2

import scala.collection.mutable.{ArrayBuffer, ListBuffer}

object e2 extends App{
  /*
  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
   */

  var fibs = ArrayBuffer(1,2)

  while(fibs(fibs.length - 1) < 4000000){
    val i = fibs.length
    val newFib = fibs(i - 1) + fibs(i - 2)
    fibs += newFib
  }

  val answer = fibs.filter(n => n % 2 == 0).sum
  println(answer)
}
